import { ASSET_AVATARS } from "../../utils/constants/paths";
import { getAssetPath } from "../../utils/appHelpers";

export const users = [
  {
    profilePic: getAssetPath(`${ASSET_AVATARS}/avatar3.jpg`, "56x56"),
    firstName: "Jannie",
    lastName: "Thompson",
    title: "Admin",
    handle: "0001",
    socialLinks: {
      facebook: "#",
      twitter: "#",
      linkedIn: "#",
    },
    summary: {
      company: "abhhh",
      branch: "adhs",
    },
    isFavorite: false,
    isOnline: true,
    isFollowing: true,
  },
  {
    profilePic: getAssetPath(`${ASSET_AVATARS}/avatar4.jpg`, "56x56"),
    firstName: "Eliza",
    lastName: "Shelton",
    title: "Admin",
    handle: "00014",
    socialLinks: {
      facebook: "#",
      twitter: "#",
      linkedIn: "#",
    },
    summary: {
      company: "abhhh",
      branch: "adhs",
    },
    isFavorite: true,
    isOnline: false,
    isFollowing: false,
  },
  {
    profilePic: getAssetPath(`${ASSET_AVATARS}/avatar5.jpg`, "56x56"),
    firstName: "Irene",
    lastName: "Owen",
    title: "Admin",
    handle: "00017",
    socialLinks: {
      facebook: "#",
      twitter: "#",
      linkedIn: "#",
    },
    summary: {
      company: "abhhh",
      branch: "adhs",
    },
    isFavorite: false,
    isOnline: true,
    isFollowing: true,
  },
  {
    profilePic: getAssetPath(`${ASSET_AVATARS}/avatar6.jpg`, "56x56"),
    firstName: "Rebeca",
    lastName: "Nunez",
    title: "Admin",
    handle: "000145",
    socialLinks: {
      facebook: "#",
      twitter: "#",
      linkedIn: "#",
    },
    summary: {
      company: "abhhh",
      branch: "adhs",
    },
    isFavorite: false,
    isOnline: true,
    isFollowing: false,
  },
  {
    profilePic: getAssetPath(`${ASSET_AVATARS}/avatar7.jpg`, "56x56"),
    firstName: "Stacy",
    lastName: "Burns",
    title: "Admin",
    handle: "00015566",
    socialLinks: {
      facebook: "#",
      twitter: "#",
      linkedIn: "#",
    },
    summary: {
      company: "abhhh",
      branch: "adhs",
    },
    isFavorite: true,
    isOnline: false,
    isFollowing: false,
  },
  {
    profilePic: getAssetPath(`${ASSET_AVATARS}/avatar8.jpg`, "56x56"),
    firstName: "Daniel",
    lastName: "Murray",
    title: "Admin",
    handle: "0001756",
    socialLinks: {
      facebook: "#",
      twitter: "#",
      linkedIn: "#",
    },
    summary: {
      company: "abhhh",
      branch: "adhs",
    },
    isFavorite: false,
    isOnline: false,
    isFollowing: false,
  },
  {
    profilePic: getAssetPath(`${ASSET_AVATARS}/avatar9.jpg`, "56x56"),
    firstName: "Rocky",
    lastName: "Hamilton",
    title: "Admin",
    handle: "0001455",
    socialLinks: {
      facebook: "#",
      twitter: "#",
      linkedIn: "#",
    },
    summary: {
      company: "abhhh",
      branch: "adhs",
    },
    isOnline: true,
    isFavorite: false,
    isFollowing: true,
  },
  {
    profilePic: getAssetPath(`${ASSET_AVATARS}/avatar10.jpg`, "56x56"),
    firstName: "Jack",
    lastName: "Brown",
    title: "Supervisor",
    handle: "000145",
    socialLinks: {
      facebook: "#",
      twitter: "#",
      linkedIn: "#",
    },
    summary: {
      company: "abhhh",
      branch: "adhs",
    },
    isFavorite: false,
    isOnline: true,
    isFollowing: true,
  },
  {
    profilePic: getAssetPath(`${ASSET_AVATARS}/avatar11.jpg`, "56x56"),
    firstName: "Mariya",
    lastName: "Gray",
    title: "Supervisor",
    handle: "0001755",
    socialLinks: {
      facebook: "#",
      twitter: "#",
      linkedIn: "#",
    },
    summary: {
      company: "abhhh",
      branch: "adhs",
    },
    isFavorite: true,
    isOnline: false,
    isFollowing: true,
  },
];
